### ISSUE TITLE
Bug cmd .tiktok

### ISSUE THREAD

**Issue by Lizz28729282** [DwiRizqiH/rem-comp-listJadibot#4]
Wi cmd .tiktok kok gk bisa 
![Uploading Screenshot_2023-05-11-07-17-26-430_com.whatsapp.jpg…]()

**Comment by Lizz28729282** [comment]
Kalo bisa gc di fix

**Comment by DwiRizqiH** [comment]
Alternatif nya bisa pakai cmd **_.ig_**

**Comment by DwiRizqiH** [comment]
Fixed!

**Comment by Jeryananda** [comment]
Kak ko jadi bot nggk ada link button
